import { Metadata } from 'next/types';
import React from 'react'
export const metadata: Metadata = {
  title: "Services",
  description: "Generated by wassim rahali",
};
const services = ()=> {
  return (
    <div>services</div>
  )
}

export default services