import { Metadata } from 'next/types';
import React from 'react'
export const metadata: Metadata = {
  title: "Contact",
  description: "Generated by wassim rahali",
};
const Contact =() =>{
  return (
    <div>Contact</div>
  )
}

export default Contact