import { Metadata } from 'next/types';
import React from 'react'
export const metadata: Metadata = {
  title: "About",
  description: "Generated by wassim rahali",
};
const About = () =>{
  return (
    <div>About</div>
  )
}

export default About