import React from "react";
import Image from "next/image";
import { Metadata } from "next/types";

interface Params {
  id: string;
}

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const id = params.id;
  const product = await fetch(`https://fakestoreapi.com/products/${id}`).then(res => res.json());

  return {
    title: `Product - ${product.title}`,
    description: "Generated by Wassim Rahali",
  };
}

const Post = async ({ params }: { params: Params }) => {
  const fetchProduct = async (id: string) => {
    const res = await fetch(`https://fakestoreapi.com/products/${id}`);
    if (!res.ok) {
      throw new Error("Failed to fetch data");
    }
    return res.json();
  };

  const data = await fetchProduct(params.id);
  console.log(data);

  return (
    <>
  
     <header className="p-6  border-b">
        <h1 className="text-2xl font-bold text-gray-800">{data.title}</h1>
        <p className="mt-2 text-gray-600">{data.description}</p>
      </header>
      
      <div className="p-6">
        <div className="flex justify-center">
        <Image
  alt={data.title}
  src={data.image}
  width={300}
  height={300}
  className="w-2/4 h-auto rounded-md"
/>

        </div>

        <div className="mt-6">
          <p className="text-gray-700">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem
            tempora aspernatur ducimus delectus itaque fuga asperiores, distinctio
            ipsam eos. Accusantium non doloremque quidem provident blanditiis,
            culpa libero nisi nam reprehenderit, eius rem magnam? Libero velit
            esse facilis laboriosam veniam dignissimos tenetur.
          </p>
        </div>
      </div>
    <div className="max-w-md mx-auto mt-12 shadow-lg rounded-lg overflow-hidden bg-white">
   
      
    </div>
    </>
  );
};

export default Post;
